Readme update
aws/amazon-braket-examples pull request #22
Opened 2020-12-11 10:14 UTC by xiaosi-xu

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2020-12-11 20:03 UTC, lundql requested changes
I made some suggestions Some are small things like a missing word. Some are suggestions to break up sentences and thereby add a bit more clarity. Thanks for letting me review this text.

2020-12-11 20:03 UTC, lundql commented on README.md
> +    This tutorial solves small instances of the famous travelling salesman problem (TSP) using D-Wave devices on Amazon Braket. TSP is an NP-hard problem in combinatorial optimization, asking for the
This tutorial solves small instances of the famous travelling salesman problem (TSP) using D-Wave devices on Amazon Braket. TSP is an NP-hard problem in combinatorial optimization. The solution finds the shortest possible route that visits each city exactly once, given a list of cities and the distances between each pair of cities. To solve the problem, cities and distances are mapped to a graph with weighted edges. A solution, when found on that graph, is the Hamiltonian cycle that has the least weight.

2020-12-11 21:26 UTC, xiaosi-xu commented
> I made some suggestions Some are small things like a missing word. Some are suggestions to break up sentences and thereby add a bit more clarity. Thanks for letting me review this text.

Thanks a lot! I have incorporated all the changes.

2021-01-28 00:58 UTC, licedric commented on README.md
> +    This tutorial solves a small instance of the famous maximum cut (MaxCut) problem using a D-Wave device on Amazon Braket. The MaxCut problem is one of the most famous NP-hard problems in combinato
```suggestion
    This tutorial solves a small instance of the famous Maximum Cut (MaxCut) problem using a D-Wave device on Amazon Braket. The MaxCut problem is one of the most famous NP-hard problems in combinatorial optimization. Given an undirected graph 𝐺(𝑉,𝐸) with a vertex set 𝑉 and an edge set 𝐸, the MaxCut problem seeks to partition 𝑉 into two sets, such that the number of edges between the two sets (considered to be severed by the cut) is as large as possible. Applications can be found in clustering problems for marketing purposes, or for portfolio optimization problems in finance. 
```

Not sure why this change was necessary - Max Cut, like most named computational problems, is generally always capitalized in the literature.

2021-01-28 00:59 UTC, licedric commented on README.md
>    * **Minimum Vertex**
Should this be minimum vertex cover?

2021-01-28 01:00 UTC, licedric commented on README.md
> +    This tutorial shows how to solve a constraint satisfaction problem (CSP) problem, with the example of factoring, using a D-Wave device on Amazon Braket. Particularly, the factoring is expressed a
```suggestion
    This tutorial shows how to solve a constraint satisfaction problem (CSP) problem, with the example of factoring, using a D-Wave device on Amazon Braket. Particularly, factoring is expressed as a CSP using Boolean logic operations, and it is converted to a binary quadratic model that can be solved by a D-Wave device.
```

2021-01-28 01:02 UTC, licedric commented on README.md
> +    This tutorial solves small instances of the famous travelling salesman problem (TSP) using D-Wave devices on Amazon Braket. TSP is an NP-hard problem in combinatorial optimization. The solution f
```suggestion
    This tutorial solves small instances of the famous traveling salesman problem (TSP) using a D-Wave device on Amazon Braket. TSP is an NP-hard problem in combinatorial optimization. The solution finds the shortest possible route that visits each city exactly once, given a list of cities and the distances between each pair of cities. To solve the problem, cities and distances are mapped to a graph with weighted edges. A solution, when found on that graph, is the Hamiltonian cycle that has the least weight.
```

2021-01-28 18:41 UTC, lundql approved these changes

2021-01-28 21:29 UTC, merged