new notebook: notification for task completion
aws/amazon-braket-examples pull request #8
Opened 2020-11-19 18:12 UTC by xiaosi-xu

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2020-11-20 00:04 UTC, lundql requested changes
Very nice work! I tightened up some things, broke up a few long sentences, implemented a few specific items of style guidance, and generally aimed toward reducing the mental overhead required from the reader. That is a general instruction for all AWS writing, even though we know our customers are very intelligent---they are also very busy!

2020-11-20 23:16 UTC, xiaosi-xu commented
> Very nice work! I tightened up some things, broke up a few long sentences, implemented a few specific items of style guidance, and generally aimed toward reducing the mental overhead required from the reader. That is a general instruction for all AWS writing, even though we know our customers are very intelligent---they are also very busy!

Thank you for the review! Your comments are quite useful. I have incorporated all the changes and made a new commit.

2020-11-20 23:43 UTC, lundql approved these changes
LGTM

2020-11-23 07:51 UTC, speller26 approved these changes

2020-11-23 19:45 UTC, merged